name: Build packages

concurrency:
  group: build-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: [ "Run fvt tests","Run test cases" ]
    types:
      - completed
    branches:
      - master
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        golang:
          - 1.20.2
        arch:
          - amd64
          - arm64

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - name: build binary packages
      run: |
        docker run -i --rm \
        -v $(pwd):/ekuiper \
        --workdir /ekuiper \
        --env KUIPER_SOURCE='/ekuiper' \
        --platform linux/${{ matrix.arch }} \
        ghcr.io/lf-edge/ekuiper/base:${{ matrix.golang }}-debian \
        bash -euc "git config --global --add safe.directory /ekuiper && make pkg_without_edgex && make pkg_core"
    - name: build docker images
      run: |
        export TAG=$(git describe --tags --always)
        export PKG=kuiper-nio-${TAG}-linux-${{ matrix.arch }}
        sudo docker buildx build --platform linux/${{ matrix.arch }} -t emqx/ekuiper:${TAG} -f deploy/docker/Dockerfile-slim-python .
        sudo docker save -o _packages/${PKG}-docker.tar emqx/ekuiper:${TAG}
        sudo chmod 644 _packages/*
    - name: create sha file
      run: |
        cd _packages && for var in $(ls); do sudo bash -c "echo $(sha256sum $var | awk '{print $1}') > $var.sha256"; done && cd -
    - uses: actions/upload-artifact@v3
      with:
        name: packages
        path: _packages/

  release:
    runs-on: ubuntu-latest

    needs:
    - build

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v1
      with:
        name: packages
        path: _packages
    - name: check packages
      run: |
        cd _packages && for var in $( ls |grep -v sha256); do
          echo "$(cat $var.sha256) $var" | sha256sum -c || exit 1
        done
    - uses: Rory-Z/upload-release-asset@v1
      if: github.event_name == 'release'
      with:
        repo: ekuiper
        path: "_packages/kuiper-*"
        token: ${{ secrets.CI_GIT_TOKEN }}
